version: "2"
services:
    spark-master:
        image: "eyalbenivri/spark2dock:sv2.1.0_v1.0"
        command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        environment:
            MASTER: spark://spark-master:7077
            SPARK_CONF_DIR: /conf
            SPARK_PUBLIC_DNS: 127.0.0.1
        ports:
            - 4040:4040
            - 6066:6066
            - 7077:7077
            - 8080:8080
        volumes:
            - ./conf:/conf
            - ./code:/code
            - ./data:/data

    spark-worker:
        image: "eyalbenivri/spark2dock:sv2.1.0_v1.0"
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        #hostname: spark-worker-1
        environment:
            SPARK_CONF_DIR: /conf
            SPARK_PUBLIC_DNS: 127.0.0.1
            SPARK_WORKER_CORES: 2
            SPARK_WORKER_MEMORY: 2g
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
        ports:
            - 8081
        volumes:
            - ./conf:/conf
            - ./data:/data